import "dotenv/config";
import { getDb } from "../api/queries/connection";
import { posts, profileBio, cvEntries, localUsers, siteSettings } from "./schema";
import bcrypt from "bcryptjs";

async function seed() {
  console.log("Seeding database...");

  // 1. Seed admin user
  const existingUsers = await getDb().select().from(localUsers);
  if (existingUsers.length === 0) {
    const passwordHash = await bcrypt.hash("123456", 12);
    await getDb().insert(localUsers).values({
      username: "admin",
      passwordHash,
      name: "Admin",
      role: "admin",
    });
    console.log("  Created admin user (admin / 123456)");
  } else {
    console.log("  Admin user already exists");
  }

  // 2. Seed chapters of Wiegers book
  const existingPosts = await getDb().select().from(posts);
  if (existingPosts.length === 0) {
    const seedPosts = [
      // ========== ЧАСТЬ I: Требования к ПО: что, почему и кто ==========
      {
        year: "I",
        image: "/images/ch1.jpg",
        sortOrder: 1,
        zhTitle: "Глава 1. Основы разработки требований к ПО",
        zhSubtitle: "Определения, уровни и типы требований, разработка и управление",
        zhCollection: "Часть I — Что, почему и кто",
        zhContent: "Введение в ключевые термины разработки требований: бизнес-требования, пользовательские требования, функциональные и нефункциональные требования. Иерархия от бизнес-целей к спецификации ПО.",
        zhDetailContent: "Каждая содержащая ПО система имеет пользователей, которые полагаются на неё. Время, которое тратится на выяснение потребностей пользователей, представляет собой высокоэффективную инвестицию в успех проекта.\n\nТРЕБОВАНИЕ — это спецификация того, что должно быть реализовано. В нём описано поведение системы, свойства системы или её атрибуты. Оно может служить ограничением в процессе разработки системы.\n\nТри уровня требований:\n• Бизнес-требования — высокоуровневые цели организации\n• Пользовательские требования — задачи пользователей\n• Функциональные требования — поведение системы\n\nТипы требований:\n• Бизнес-правила — политики, стандарты, регуляции\n• Ограничения — границы выбора для разработчика\n• Атрибуты качества — производительность, безопасность, usability\n• Внешние интерфейсы — взаимодействие с другими системами\n\nРазработка требований включает: выявление, анализ, документирование и утверждение. Управление требованиями включает: версионирование, отслеживание изменений, анализ влияния.\n\nОсновные проблемы: недостаточное вовлечение пользователей, небрежное планирование, разрастание требований, двусмысленность, требования-«бантики», пропущенные классы пользователей.",
        enTitle: "Chapter 1. Software Requirements Development Fundamentals",
        enSubtitle: "Definitions, levels and types of requirements, development and management",
        enCollection: "Part I — What, Why and Who",
        enContent: "Introduction to key terms in requirements development: business requirements, user requirements, functional and non-functional requirements. Hierarchy from business goals to software specification.",
        enDetailContent: "Every software-containing system has users who rely on it. Time spent understanding user needs is a highly effective investment in project success.\n\nA REQUIREMENT is a specification of what should be implemented. It describes system behavior, properties, or attributes. It may serve as a constraint in the system development process.\n\nThree levels of requirements:\n• Business requirements — high-level organizational goals\n• User requirements — user tasks\n• Functional requirements — system behavior\n\nRequirement types:\n• Business rules — policies, standards, regulations\n• Constraints — developer choice boundaries\n• Quality attributes — performance, security, usability\n• External interfaces — interaction with other systems\n\nRequirements development includes: elicitation, analysis, specification, and validation. Requirements management includes: versioning, change tracking, and impact analysis.\n\nKey problems: insufficient user involvement, careless planning, requirements creep, ambiguity, gold plating, missed user classes.",
      },
      {
        year: "I",
        image: "/images/ch2.jpg",
        sortOrder: 2,
        zhTitle: "Глава 2. Требования с точки зрения клиента",
        zhSubtitle: "Разрыв ожиданий, права и обязанности клиента",
        zhCollection: "Часть I — Что, почему и кто",
        zhContent: "Анализ взаимоотношений между клиентами и разработчиками. Билль о правах клиента ПО и билль об обязанностях. Партнёрство как основа успеха проекта.",
        zhDetailContent: "Без адекватного участия клиента в конце проекта неизбежно возникает РАЗРЫВ ОЖИДАНИЙ — пробел между тем, что клиенту реально нужно, и тем, что предоставили разработчики.\n\nЗаинтересованное лицо (stakeholder) — человек, группа или организация, активно задействованная в проекте, подверженная влиянию процесса или результата, либо способная влиять на них.\n\nКлиент — заинтересованное лицо, запрашивающее, оплачивающее, выбирающее, определяющее, использующее и получающее результаты работы программного продукта.\n\nБИЛЛЬ О ПРАВАХ КЛИЕНТА ПО:\n1. Право на ожидание от аналитиков знания предметной области\n2. Право на ожидание от аналитиков организованности\n3. Право на получение вариантов решений\n4. Право на описание характеристик качества\n5. Право на прототипы до начала кодирования\n6. Право на чёткое определение приоритетов\n7. Право на доступ к базовой версии требований\n8. Право на получение изменений в управляемом режиме\n9. Право на окружение, способствующее продуктивной работе\n10. Право на профессиональное отношение\n\nБИЛЛЬ ОБ ОБЯЗАННОСТЯХ КЛИЕНТА ПО:\n1. Обязанность рассказать о бизнес-целях\n2. Обязанность активно участвовать в выявлении\n3. Обязанность описывать задачи, а не решения\n4. Обязанность уточнять терминологию\n5. Обязанность принимать решения о приоритетах\n6. Обязанность проверять требования\n7. Обязанность создавать прототипы интерфейсов\n8. Обязанность рецензировать спецификации\n9. Обязанность уважать границы проекта\n10. Обязанность принимать базовую версию требований",
        enTitle: "Chapter 2. Requirements from the Customer's Perspective",
        enSubtitle: "Expectation gap, rights and responsibilities of the customer",
        enCollection: "Part I — What, Why and Who",
        enContent: "Analysis of client-developer relationships. Software Customer's Bill of Rights and Bill of Responsibilities. Partnership as the foundation of project success.",
        enDetailContent: "Without adequate customer involvement, an EXPECTATION GAP inevitably emerges at the end of a project — the gap between what the customer actually needs and what developers have delivered.\n\nA STAKEHOLDER is a person, group, or organization actively involved in a project, affected by the process or outcome, or capable of influencing them.\n\nA CUSTOMER is a stakeholder who requests, pays for, selects, determines, uses, and receives the results of a software product.\n\nCUSTOMER'S BILL OF RIGHTS:\n1. Right to expect analysts to know the business domain\n2. Right to expect analysts to be organized\n3. Right to receive alternative solutions\n4. Right to description of quality attributes\n5. Right to prototypes before coding begins\n6. Right to clear priority definitions\n7. Right to access to requirements baseline\n8. Right to receive changes in a controlled manner\n9. Right to an environment conducive to productive work\n10. Right to professional treatment\n\nCUSTOMER'S BILL OF RESPONSIBILITIES:\n1. Responsibility to share business goals\n2. Responsibility to actively participate in elicitation\n3. Responsibility to describe tasks, not solutions\n4. Responsibility to clarify terminology\n5. Responsibility to make priority decisions\n6. Responsibility to review requirements\n7. Responsibility to create interface prototypes\n8. Responsibility to review specifications\n9. Responsibility to respect project boundaries\n10. Responsibility to accept requirements baseline",
      },
      {
        year: "I",
        image: "/images/ch3.jpg",
        sortOrder: 3,
        zhTitle: "Глава 3. Рекомендуемые приёмы формулирования требований",
        zhSubtitle: "Каркас процесса: выявление, анализ, спецификация, проверка",
        zhCollection: "Часть I — Что, почему и кто",
        zhContent: "Обзор десятков проверенных практик создания и управления требованиями. Как внедрить процесс разработки требований в организации.",
        zhDetailContent: "КАРКАС ПРОЦЕССА СОЗДАНИЯ ТРЕБОВАНИЙ:\n\n1. ВЫЯВЛЕНИЕ (Elicitation)\n• Интервью с заинтересованными лицами\n• Семинары и фокус-группы\n• Наблюдение за пользователями\n• Анализ существующих документов\n• Создание прототипов\n• Изучение конкурентов\n\n2. АНАЛИЗ (Analysis)\n• Разложение требований\n• Моделирование процессов\n• Выявление конфликтов и неопределённостей\n• Приоритизация\n\n3. СПЕЦИФИКАЦИЯ (Specification)\n• Документирование в стандартных формах\n• Использование шаблонов SRS\n• Модели анализа и диаграммы\n\n4. ПРОВЕРКА (Validation)\n• Рецензирование требований\n• Создание тестовых сценариев\n• Прототипирование\n• Моделирование\n\nУПРАВЛЕНИЕ ТРЕБОВАНИЯМИ:\n• Определение базовой версии\n• Контроль изменений\n• Отслеживание состояния\n• Анализ влияния изменений\n\nОБУЧЕНИЕ:\nВнедрение новых приёмов требует обучения команды, менеджеров и клиентов. Начните с небольших улучшений, но начните сегодня.",
        enTitle: "Chapter 3. Recommended Practices for Requirements Development",
        enSubtitle: "Process framework: elicitation, analysis, specification, validation",
        enCollection: "Part I — What, Why and Who",
        enContent: "Overview of dozens of proven practices for creating and managing requirements. How to implement a requirements development process in an organization.",
        enDetailContent: "REQUIREMENTS DEVELOPMENT PROCESS FRAMEWORK:\n\n1. ELICITATION\n• Stakeholder interviews\n• Workshops and focus groups\n• User observation\n• Analysis of existing documents\n• Prototyping\n• Competitive analysis\n\n2. ANALYSIS\n• Requirements decomposition\n• Process modeling\n• Conflict and ambiguity resolution\n• Prioritization\n\n3. SPECIFICATION\n• Documentation in standard forms\n• Using SRS templates\n• Analysis models and diagrams\n\n4. VALIDATION\n• Requirements reviews\n• Test scenario creation\n• Prototyping\n• Modeling\n\nREQUIREMENTS MANAGEMENT:\n• Baseline definition\n• Change control\n• Status tracking\n• Impact analysis of changes\n\nTRAINING:\nImplementing new practices requires training the team, managers, and customers. Start with small improvements, but start today.",
      },
      {
        year: "I",
        image: "/images/ch4.jpg",
        sortOrder: 4,
        zhTitle: "Глава 4. Бизнес-аналитик",
        zhSubtitle: "Роль, задачи, навыки и становление аналитика",
        zhCollection: "Часть I — Что, почему и кто",
        zhContent: "Кто такой бизнес-аналитик, какие навыки ему нужны, как аналитик взаимодействует с командой в проектах гибкой разработки.",
        zhDetailContent: "РОЛЬ БИЗНЕС-АНАЛИТИКА:\nБизнес-аналитик — это роль в проекте, которая прежде всего отвечает за действия по работе с требованиями. У этой роли есть и другие имены: системный аналитик, аналитик требований, product owner.\n\nЗАДАЧИ АНАЛИТИКА:\n• Выявление и документирование бизнес-требований\n• Работа с пользователями для понимания их задач\n• Формулирование функциональных и нефункциональных требований\n• Анализ и моделирование требований\n• Проверка и утверждение требований\n• Управление изменениями требований\n• Обучение команды и клиентов\n\nНАВЫКИ АНАЛИТИКА:\n• Коммуникативные навыки — слушание, интервьюирование\n• Аналитическое мышление — декомпозиция, абстракция\n• Знание предметной области\n• Навыки моделирования\n• Умение работать с конфликтами\n• Лидерские качества\n\nСТАНОВЛЕНИЕ АНАЛИТИКА:\nАналитики приходят из разных ролей — бывшие пользователи, разработчики, тестировщики, менеджеры проектов, специалисты предметной области. Каждый путь имеет свои преимущества.\n\nВ проектах гибкой разработки роль аналитика часто распределяется между product owner и командой разработки.",
        enTitle: "Chapter 4. The Business Analyst",
        enSubtitle: "Role, tasks, skills and becoming an analyst",
        enCollection: "Part I — What, Why and Who",
        enContent: "Who is a business analyst, what skills are needed, how the analyst interacts with the team in agile development projects.",
        enDetailContent: "ROLE OF THE BUSINESS ANALYST:\nA business analyst is a role in a project that is primarily responsible for requirements-related activities. This role has other names: systems analyst, requirements analyst, product owner.\n\nANALYST TASKS:\n• Eliciting and documenting business requirements\n• Working with users to understand their tasks\n• Formulating functional and non-functional requirements\n• Analyzing and modeling requirements\n• Reviewing and approving requirements\n• Managing requirement changes\n• Training the team and clients\n\nANALYST SKILLS:\n• Communication skills — listening, interviewing\n• Analytical thinking — decomposition, abstraction\n• Domain knowledge\n• Modeling skills\n• Conflict resolution\n• Leadership qualities\n\nBECOMING AN ANALYST:\nAnalysts come from different roles — former users, developers, testers, project managers, domain specialists. Each path has its advantages.\n\nIn agile development projects, the analyst role is often distributed between the product owner and the development team.",
      },
      // ========== ЧАСТЬ II: Разработка требований ==========
      {
        year: "II",
        image: "/images/ch5.jpg",
        sortOrder: 5,
        zhTitle: "Глава 5. Определение бизнес-требований",
        zhSubtitle: "Документ о концепции и границах проекта",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Как формулировать бизнес-требования, определять границы проекта и создавать документ концепции и границ (Vision and Scope).",
        zhDetailContent: "БИЗНЕС-ТРЕБОВАНИЯ описывают, почему организации нужна система — то есть цели, которые организация намерена достичь с её помощью. Они обычно высказываются теми, кто финансирует проект: заказчиками, маркетологами, руководством.\n\nДОКУМЕНТ О КОНЦЕПЦИИ И ГРАНИЦАХ содержит:\n\n1. Бизнес-требования:\n• Бизнес-возможности (зачем нужна система)\n• Бизнес-цели и критерии успеха\n• Потребности клиентов\n• Конкурентная аналитика\n\n2. Рамки и ограничения проекта:\n• Возможности релиза (что входит)\n• Ограничения (бюджет, сроки, технологии)\n• Критерии приёмки\n\n3. Бизнес-контекст:\n• Профили заинтересованных лиц\n• Приоритеты проекта\n• Окружение работы\n\nСПОСОБЫ ПРЕДСТАВЛЕНИЯ ГРАНИЦ:\n• Контекстная диаграмма (система и внешние сущности)\n• Карта экосистемы\n• Дерево функций\n• Список событий\n\nВ проектах гибкой разработки концепция и границы определяются на уровне продукта и эпиков.",
        enTitle: "Chapter 5. Defining Business Requirements",
        enSubtitle: "Vision and scope document",
        enCollection: "Part II — Requirements Development",
        enContent: "How to formulate business requirements, define project boundaries, and create the Vision and Scope document.",
        enDetailContent: "BUSINESS REQUIREMENTS describe why the organization needs a system — the goals the organization intends to achieve with its help. They are usually expressed by those who fund the project: customers, marketers, management.\n\nVISION AND SCOPE DOCUMENT contains:\n\n1. Business Requirements:\n• Business opportunities (why the system is needed)\n• Business goals and success criteria\n• Customer needs\n• Competitive analysis\n\n2. Project Boundaries and Constraints:\n• Release scope (what's included)\n• Constraints (budget, timeline, technology)\n• Acceptance criteria\n\n3. Business Context:\n• Stakeholder profiles\n• Project priorities\n• Operating environment\n\nWAYS TO REPRESENT BOUNDARIES:\n• Context diagram (system and external entities)\n• Ecosystem map\n• Feature tree\n• Event list\n\nIn agile projects, vision and scope are defined at the product and epic level.",
      },
      {
        year: "II",
        image: "/images/ch6.jpg",
        sortOrder: 6,
        zhTitle: "Глава 6. Как отобрать пользователей для работы над проектом",
        zhSubtitle: "Классы пользователей, представители, сторонники продукта",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Методы идентификации классов пользователей, выбора представителей, работа со сторонниками продукта (product champions).",
        zhDetailContent: "КЛАССЫ ПОЛЬЗОВАТЕЛЕЙ — группы людей с разными потребностями, которые будут использовать продукт по-разному. Каждый класс имеет свои характеристики: частота использования, привилегии, опыт, задачи.\n\nАРХЕТИПЫ ПОЛЬЗОВАТЕЛЕЙ (User Personas):\n• Вымышленные персонажи, представляющие классы пользователей\n• Имя, фото, описание, цели, боли\n• Помогают команде эмпатизировать с пользователями\n\nПРЕДСТАВИТЕЛИ ПОЛЬЗОВАТЕЛЕЙ:\n• Должны представлять свой класс пользователей\n• Должны быть доступны для консультаций\n• Должны иметь полномочия принимать решения\n• Желательно — коммуникабельны и заинтересованы\n\nСТОРОННИК ПРОДУКТА (Product Champion):\nЧеловек из среды пользователей, который тесно работает с командой разработки. Он:\n• Представляет интересы своего класса пользователей\n• Участвует в выявлении требований\n• Проверяет требования и прототипы\n• Помогает устранять противоречия\n\nВ проектах гибкой разработки product owner выполняет роль сторонника продукта.",
        enTitle: "Chapter 6. Selecting Users for the Project",
        enSubtitle: "User classes, representatives, and product champions",
        enCollection: "Part II — Requirements Development",
        enContent: "Methods for identifying user classes, selecting representatives, and working with product champions.",
        enDetailContent: "USER CLASSES are groups of people with different needs who will use the product differently. Each class has its own characteristics: frequency of use, privileges, experience, tasks.\n\nUSER PERSONAS:\n• Fictional characters representing user classes\n• Name, photo, description, goals, pain points\n• Help the team empathize with users\n\nUSER REPRESENTATIVES:\n• Must represent their user class\n• Must be available for consultation\n• Must have decision-making authority\n• Preferably — communicative and interested\n\nPRODUCT CHAMPION:\nA person from the user environment who works closely with the development team. They:\n• Represent the interests of their user class\n• Participate in requirements elicitation\n• Review requirements and prototypes\n• Help resolve conflicts\n\nIn agile projects, the product owner serves as the product champion.",
      },
      {
        year: "II",
        image: "/images/ch7.jpg",
        sortOrder: 7,
        zhTitle: "Глава 7. Выявление требований",
        zhSubtitle: "Интервью, семинары, фокус-группы, наблюдение",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Практические методы сбора требований: как подготовиться, провести интервью, обработать результаты и понять, что сбор завершён.",
        zhDetailContent: "МЕТОДЫ ВЫЯВЛЕНИЯ ТРЕБОВАНИЙ:\n\nИНТЕРВЬЮ:\n• Наиболее распространённый метод\n• Индивидуальные и групповые\n• Структурированные и свободные\n• Подготовка вопросов заранее\n• Запись и протоколирование\n\nСЕМИНАРЫ (Workshops):\n• Интенсивные совместные сессии\n• Совместное создание требований\n• Моделирование бизнес-процессов\n• Быстрое достижение согласия\n\nФОКУС-ГРУППЫ:\n• Групповое обсуждение с модератором\n• Выявление неявных потребностей\n• Проверка концепций\n\nНАБЛЮДЕНИЕ:\n• Изучение пользователей в их естественной среде\n• Выявление неявных требований\n• Обнаружение разрывов между 'сказанным' и 'сделанным'\n\nОПРОСНЫЕ ЛИСТЫ:\n• Для больших групп пользователей\n• Количественные данные\n• Статистический анализ\n\nКАК ПОНЯТЬ, ЧТО СБОР ЗАВЕРШЁН:\n• Пользователи начинают повторяться\n• Новые требования не относятся к рамкам проекта\n• Модели становятся стабильными\n• Заинтересованные лица подтверждают полноту",
        enTitle: "Chapter 7. Requirements Elicitation",
        enSubtitle: "Interviews, workshops, focus groups, observation",
        enCollection: "Part II — Requirements Development",
        enContent: "Practical methods for gathering requirements: how to prepare, conduct interviews, process results, and know when collection is complete.",
        enDetailContent: "REQUIREMENTS ELICITATION METHODS:\n\nINTERVIEWS:\n• Most common method\n• Individual and group\n• Structured and unstructured\n• Prepare questions in advance\n• Recording and documentation\n\nWORKSHOPS:\n• Intensive collaborative sessions\n• Joint requirements development\n• Business process modeling\n• Rapid consensus building\n\nFOCUS GROUPS:\n• Group discussion with moderator\n• Identifying implicit needs\n• Concept validation\n\nOBSERVATION:\n• Studying users in their natural environment\n• Revealing implicit requirements\n• Discovering gaps between 'said' and 'done'\n\nQUESTIONNAIRES:\n• For large user groups\n• Quantitative data\n• Statistical analysis\n\nHOW TO KNOW COLLECTION IS COMPLETE:\n• Users start repeating themselves\n• New requirements fall outside project scope\n• Models become stable\n• Stakeholders confirm completeness",
      },
      {
        year: "II",
        image: "/images/ch8.jpg",
        sortOrder: 8,
        zhTitle: "Глава 8. Как понять требования пользователей",
        zhSubtitle: "Варианты использования и сценарии использования",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Подход с использованием вариантов использования (use cases) для документирования пользовательских требований.",
        zhDetailContent: "ВАРИАНТ ИСПОЛЬЗОВАНИЯ описывает последовательность действий, которую система выполняет для получения значимого результата для конкретного пользователя (актора).\n\nСТРУКТУРА ВАРИАНТА ИСПОЛЬЗОВАНИЯ:\n• Название (глагол + объект)\n• Акторы (кто инициирует)\n• Предварительные условия\n• Основной сценарий (happy path)\n• Альтернативные сценарии\n• Исключительные ситуации\n• Выходные условия\n\nПРЕИМУЩЕСТВА ПОДХОДА:\n• Ориентирован на пользователя, а не на интерфейс\n• Связывает пользовательские требования с функциональными\n• Обеспечивает контекст для функциональных требований\n• Удобен для проверки полноты\n\nПРИМЕР:\nНазвание: 'Зарегистрироваться на рейс'\nАктор: Пассажир\nОсновной сценарий:\n1. Пассажир выбирает рейс\n2. Система отображает свободные места\n3. Пассажир выбирает место\n4. Система подтверждает регистрацию\n5. Система печатает посадочный талон\n\nАльтернатива: выбор специального питания\nИсключение: рейс отменён\n\nВАЖНО: варианты использования описывают ЧТО система делает, а не КАК. Они не содержат дизайна интерфейса.",
        enTitle: "Chapter 8. Understanding User Requirements",
        enSubtitle: "Use cases and usage scenarios",
        enCollection: "Part II — Requirements Development",
        enContent: "The use case approach for documenting user requirements.",
        enDetailContent: "A USE CASE describes a sequence of actions a system performs to yield a meaningful result for a particular user (actor).\n\nUSE CASE STRUCTURE:\n• Name (verb + object)\n• Actors (who initiates)\n• Pre-conditions\n• Main scenario (happy path)\n• Alternative scenarios\n• Exceptional situations\n• Post-conditions\n\nADVANTAGES OF THE APPROACH:\n• User-oriented, not interface-oriented\n• Links user requirements to functional requirements\n• Provides context for functional requirements\n• Facilitates completeness checking\n\nEXAMPLE:\nName: 'Check in for a flight'\nActor: Passenger\nMain scenario:\n1. Passenger selects a flight\n2. System displays available seats\n3. Passenger selects a seat\n4. System confirms check-in\n5. System prints boarding pass\n\nAlternative: special meal selection\nException: flight cancelled\n\nIMPORTANT: use cases describe WHAT the system does, not HOW. They do not contain interface design.",
      },
      {
        year: "II",
        image: "/images/ch9.jpg",
        sortOrder: 9,
        zhTitle: "Глава 9. Игра по правилам",
        zhSubtitle: "Бизнес-правила и их влияние на требования",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Классификация бизнес-правил, их документирование и связь с требованиями к ПО.",
        zhDetailContent: "БИЗНЕС-ПРАВИЛО — политика, предписание, стандарт или правило, определяющее или ограничивающее некоторые стороны бизнес-процессов. По своей сути это НЕ требование к ПО, но служит источником требований.\n\nКЛАССИФИКАЦИЯ БИЗНЕС-ПРАВИЛ:\n\n1. ФАКТЫ — непреложные истины о бизнесе\nПример: 'У каждого заказа есть дата создания'\n\n2. ОГРАНИЧЕНИЯ — пределы возможностей\nПример: 'Кредитный лимит клиента не может превышать $50,000'\n\n3. АКТИВАТОРЫ ОПЕРАЦИЙ — условия, запускающие действия\nПример: 'Если заказ превышает $10,000 — требуется одобрение менеджера'\n\n4. ВЫВОДЫ — логические следствия\nПример: 'Если клиент сделал 5 заказов — он становится VIP'\n\n5. ВЫЧИСЛЕНИЯ — формулы и алгоритмы\nПример: 'НДС = сумма заказа × 20%'\n\nДОКУМЕНТИРОВАНИЕ:\nБизнес-правила хранятся отдельно от требований к ПО — обычно в каталоге бизнес-правил. Каждое правило имеет уникальный идентификатор, описание, источник и статус.",
        enTitle: "Chapter 9. Playing by the Rules",
        enSubtitle: "Business rules and their impact on requirements",
        enCollection: "Part II — Requirements Development",
        enContent: "Classification of business rules, their documentation, and relationship to software requirements.",
        enDetailContent: "A BUSINESS RULE is a policy, directive, standard, or rule that defines or constrains some aspect of business processes. It is NOT a software requirement by nature, but serves as a source of requirements.\n\nCLASSIFICATION OF BUSINESS RULES:\n\n1. FACTS — incontrovertible truths about the business\nExample: 'Every order has a creation date'\n\n2. CONSTRAINTS — limits on what is possible\nExample: 'Customer credit limit cannot exceed $50,000'\n\n3. ACTION ENABLERS — conditions that trigger actions\nExample: 'If an order exceeds $10,000 — manager approval is required'\n\n4. INFERENCES — logical consequences\nExample: 'If a customer places 5 orders — they become VIP'\n\n5. COMPUTATIONS — formulas and algorithms\nExample: 'VAT = order amount × 20%'\n\nDOCUMENTATION:\nBusiness rules are stored separately from software requirements — usually in a business rules catalog. Each rule has a unique identifier, description, source, and status.",
      },
      {
        year: "II",
        image: "/images/ch10.jpg",
        sortOrder: 10,
        zhTitle: "Глава 10. Документирование требований",
        zhSubtitle: "Спецификация требований к ПО и её структура",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Как создавать спецификацию требований к ПО (SRS), шаблоны документов, требования в проектах гибкой разработки.",
        zhDetailContent: "СПЕЦИФИКАЦИЯ ТРЕБОВАНИЙ К ПО (SRS) — документ, описывающий ожидаемое поведение системы. Используется при разработке, тестировании, управлении проектом.\n\nШАБЛОН SRS:\n\n1. Введение\n• Цели документа\n• Область применения\n• Определения и аббревиатуры\n• Ссылки\n\n2. Общее описание\n• Видение продукта\n• Классы пользователей\n• Окружение работы\n• Ограничения проекта\n• Предположения и зависимости\n\n3. Функции системы\n• Функциональные требования (с уникальными идентификаторами)\n• Варианты использования\n\n4. Требования к данным\n• Модели данных\n• Словарь данных\n\n5. Требования к внешним интерфейсам\n• Пользовательские интерфейсы\n• Аппаратные интерфейсы\n• Программные интерфейсы\n• Коммуникационные интерфейсы\n\n6. Атрибуты качества\n• Производительность\n• Безопасность\n• Надёжность\n• Удобство использования\n\n7. Требования по интернационализации\n\nВ проектах гибкой разработки SRS часто заменяется набором пользовательских историй с критериями приёмки.",
        enTitle: "Chapter 10. Documenting Requirements",
        enSubtitle: "Software Requirements Specification and its structure",
        enCollection: "Part II — Requirements Development",
        enContent: "How to create a Software Requirements Specification (SRS), document templates, requirements in agile projects.",
        enDetailContent: "SOFTWARE REQUIREMENTS SPECIFICATION (SRS) — a document describing the expected system behavior. Used in development, testing, and project management.\n\nSRS TEMPLATE:\n\n1. Introduction\n• Document purpose\n• Scope\n• Definitions and acronyms\n• References\n\n2. Overall Description\n• Product vision\n• User classes\n• Operating environment\n• Project constraints\n• Assumptions and dependencies\n\n3. System Features\n• Functional requirements (with unique IDs)\n• Use cases\n\n4. Data Requirements\n• Data models\n• Data dictionary\n\n5. External Interface Requirements\n• User interfaces\n• Hardware interfaces\n• Software interfaces\n• Communication interfaces\n\n6. Quality Attributes\n• Performance\n• Security\n• Reliability\n• Usability\n\n7. Internationalization Requirements\n\nIn agile projects, SRS is often replaced by a set of user stories with acceptance criteria.",
      },
      {
        year: "II",
        image: "/images/ch11.jpg",
        sortOrder: 11,
        zhTitle: "Глава 11. Пишем идеальные требования",
        zhSubtitle: "Характеристики качественных требований и принципы написания",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Какие характеристики должны иметь хорошие требования, как избежать неопределённости и неполноты.",
        zhDetailContent: "ХАРАКТЕРИСТИКИ ПРЕВОСХОДНЫХ ТРЕБОВАНИЙ:\n\nДля ОТДЕЛЬНЫХ требований:\n• Корректность — отражает реальную потребность\n• Однозначность — одинаково понимается всеми\n• Полнота — не пропущена важная информация\n• Проверяемость — можно протестировать\n• Модифицируемость — легко изменить\n• Тraceability — имеет уникальный идентификатор\n\nДля НАБОРОВ требований:\n• Полнота — все требования учтены\n• Непротиворечивость — нет конфликтов\n• Модифицируемость — структура позволяет изменять\n• Ранжируемость — можно расставить приоритеты\n\nПРИНЦИПЫ СОЗДАНИЯ:\n\n1. Системная vs пользовательская точка зрения\n'Система должна...' vs 'Пользователь может...'\n\n2. Язык и стиль\n• Используйте 'должен' для обязательных\n• Избегайте 'может', 'будет', 'должен бы'\n• Одно действие на одно требование\n\n3. Предотвращение неопределённости\n• Избегайте: удобный, быстрый, большой, гибкий\n• Избегайте: и т.д., и т.п., как правило\n• Используйте конкретные числа\n\n4. Предотвращение неполноты\n• Указывайте граничные условия\n• Описывайте реакцию на ошибки\n• Не пропускайте 'очевидное'",
        enTitle: "Chapter 11. Writing Excellent Requirements",
        enSubtitle: "Characteristics of quality requirements and writing principles",
        enCollection: "Part II — Requirements Development",
        enContent: "What characteristics good requirements should have, how to avoid ambiguity and incompleteness.",
        enDetailContent: "CHARACTERISTICS OF EXCELLENT REQUIREMENTS:\n\nFor INDIVIDUAL requirements:\n• Correctness — reflects real need\n• Unambiguity — understood the same by all\n• Completeness — no important information missing\n• Verifiability — can be tested\n• Modifiability — easy to change\n• Traceability — has a unique identifier\n\nFor SETS of requirements:\n• Completeness — all requirements accounted for\n• Consistency — no conflicts\n• Modifiability — structure allows changes\n• Rankability — can be prioritized\n\nCREATION PRINCIPLES:\n\n1. System vs User Perspective\n'System shall...' vs 'User can...'\n\n2. Language and Style\n• Use 'shall' for mandatory\n• Avoid 'may', 'will', 'should'\n• One action per requirement\n\n3. Preventing Ambiguity\n• Avoid: convenient, fast, large, flexible\n• Avoid: etc., and so on, typically\n• Use specific numbers\n\n4. Preventing Incompleteness\n• Specify boundary conditions\n• Describe error handling\n• Don't skip the 'obvious'",
      },
      {
        year: "II",
        image: "/images/ch12.jpg",
        sortOrder: 12,
        zhTitle: "Глава 12. Лучше один раз увидеть, чем 1024 раза услышать",
        zhSubtitle: "Моделирование требований: диаграммы, модели, визуализация",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Визуальное моделирование требований: диаграммы потоков данных, swimlane, состояний, UML.",
        zhDetailContent: "МОДЕЛИРОВАНИЕ ТРЕБОВАНИЙ помогает представить знания о требованиях в наглядной форме и обнаружить пробелы.\n\nДИАГРАММА ПОТОКОВ ДАННЫХ (DFD):\n• Показывает преобразование данных процессами\n• Внешние сущности → Процессы → Хранилища данных\n• Уровни: контекстная (0), декомпозиция (1, 2...)\n\nДИАГРАММА SWIMLANE:\n• Показывает бизнес-процессы с разделением по ролям\n• Каждая 'дорожка' — ответственный за этап\n• Хорошо показывает взаимодействие между отделами\n\nДИАГРАММА ПЕРЕХОДОВ СОСТОЯНИЙ:\n• Показывает жизненный цикл объекта\n• Состояния → События → Переходы\n• Полезна для объектов со сложным поведением\n\nКАРТА ДИАЛОГОВЫХ ОКОН:\n• Структура экранов пользовательского интерфейса\n• Переходы между экранами\n• Иерархия навигации\n\nТАБЛИЦЫ РЕШЕНИЙ:\n• Систематизируют сложную бизнес-логику\n• Условия × Действия = Правила\n\nUML-ДИАГРАММЫ:\n• Диаграммы классов, последовательностей, активностей\n• Стандарт в отрасли ПО",
        enTitle: "Chapter 12. A Picture Is Worth 1024 Words",
        enSubtitle: "Requirements modeling: diagrams, models, visualization",
        enCollection: "Part II — Requirements Development",
        enContent: "Visual requirements modeling: data flow diagrams, swimlane, state charts, UML.",
        enDetailContent: "REQUIREMENTS MODELING helps present knowledge about requirements in visual form and discover gaps.\n\nDATA FLOW DIAGRAM (DFD):\n• Shows data transformation by processes\n• External entities → Processes → Data stores\n• Levels: context (0), decomposition (1, 2...)\n\nSWIMLANE DIAGRAM:\n• Shows business processes with role separation\n• Each 'lane' — responsible party\n• Clearly shows inter-departmental interaction\n\nSTATE TRANSITION DIAGRAM:\n• Shows object lifecycle\n• States → Events → Transitions\n• Useful for objects with complex behavior\n\nDIALOG MAP:\n• Structure of user interface screens\n• Screen transitions\n• Navigation hierarchy\n\nDECISION TABLES:\n• Systematize complex business logic\n• Conditions × Actions = Rules\n\nUML DIAGRAMS:\n• Class, sequence, activity diagrams\n• Industry standard in software",
      },
      {
        year: "II",
        image: "/images/ch13.jpg",
        sortOrder: 13,
        zhTitle: "Глава 13. Определение требований к данным",
        zhSubtitle: "Моделирование данных, словари данных, спецификация отчётов",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Как определять требования к данным: модели отношений, словари данных, панели мониторинга.",
        zhDetailContent: "ТРЕБОВАНИЯ К ДАННЫМ описывают структуру, отношения, атрибуты и правила обработки данных в системе.\n\nМОДЕЛИРОВАНИЕ ОТНОШЕНИЙ ДАННЫХ:\n• ER-диаграммы (сущность-связь)\n• Классы данных и их атрибуты\n• Связи: 1:1, 1:N, M:N\n\nСЛОВАРЬ ДАННЫХ:\n• Состав (сущности, атрибуты)\n• Определения и форматы\n• Правила валидации\n• Источники данных\n\nАНАЛИЗ ДАННЫХ:\n• Какие данные создаются, используются, удаляются\n• Жизненный цикл данных\n• Требования к хранению и архивированию\n\nСПЕЦИФИКАЦИЯ ОТЧЁТОВ:\n• Назначение отчёта\n• Периодичность\n• Поля и формат\n• Критерии фильтрации\n• Правила сортировки\n• Примеры вывода\n\nПАНЕЛИ МОНИТОРИНГА (Dashboards):\n• Ключевые показатели (KPI)\n• Реальное время vs периодические\n• Настраиваемость представления",
        enTitle: "Chapter 13. Defining Data Requirements",
        enSubtitle: "Data modeling, data dictionaries, report specifications",
        enCollection: "Part II — Requirements Development",
        enContent: "How to define data requirements: relationship models, data dictionaries, dashboards.",
        enDetailContent: "DATA REQUIREMENTS describe the structure, relationships, attributes, and processing rules of data in a system.\n\nDATA RELATIONSHIP MODELING:\n• ER diagrams (entity-relationship)\n• Data classes and their attributes\n• Relationships: 1:1, 1:N, M:N\n\nDATA DICTIONARY:\n• Composition (entities, attributes)\n• Definitions and formats\n• Validation rules\n• Data sources\n\nDATA ANALYSIS:\n• What data is created, used, deleted\n• Data lifecycle\n• Storage and archiving requirements\n\nREPORT SPECIFICATIONS:\n• Report purpose\n• Frequency\n• Fields and format\n• Filter criteria\n• Sorting rules\n• Sample output\n\nDASHBOARDS:\n• Key Performance Indicators (KPI)\n• Real-time vs periodic\n• Customizable presentation",
      },
      {
        year: "II",
        image: "/images/ch14.jpg",
        sortOrder: 14,
        zhTitle: "Глава 14. Атрибуты качества ПО",
        zhSubtitle: "Нефункциональные требования: производительность, безопасность, надёжность",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Полный обзор нефункциональных требований: внешние и внутренние атрибуты качества, язык Planguage.",
        zhDetailContent: "АТРИБУТЫ КАЧЕСТВА ПО — это нефункциональные требования, описывающие характеристики сервиса или производительности продукта.\n\nВНЕШНИЕ АТРИБУТЫ КАЧЕСТВА:\n\n1. ДОСТУПНОСТЬ (Availability)\n• Время безотказной работы (например, 99.9%)\n• Время восстановления после сбоя\n\n2. ПРОИЗВОДИТЕЛЬНОСТЬ (Performance)\n• Время отклика (например, < 2 секунд)\n• Пропускная способность\n• Ёмкость системы\n\n3. БЕЗОПАСНОСТЬ (Security)\n• Аутентификация и авторизация\n• Шифрование данных\n• Аудит действий\n\n4. УДОБСТВО ИСПОЛЬЗОВАНИЯ (Usability)\n• Время обучения нового пользователя\n• Количество ошибок при работе\n• Удовлетворённость пользователей\n\n5. МАСШТАБИРУЕМОСТЬ (Scalability)\n\nВНУТРЕННИЕ АТРИБУТЫ:\n• Модифицируемость\n• Переносимость\n• Тестируемость\n• Повторное использование\n\nЯЗЫК PLANGUAGE — формализованный способ записи требований к качеству:\n'Тег: Доступность системы\nМасштаб: Процент времени безотказной работы\nМетод измерения: Мониторинг за 30 дней\nМинимум: 99.5%\nЦель: 99.9%'",
        enTitle: "Chapter 14. Software Quality Attributes",
        enSubtitle: "Non-functional requirements: performance, security, reliability",
        enCollection: "Part II — Requirements Development",
        enContent: "Complete overview of non-functional requirements: external and internal quality attributes, Planguage.",
        enDetailContent: "SOFTWARE QUALITY ATTRIBUTES are non-functional requirements describing service characteristics or product performance.\n\nEXTERNAL QUALITY ATTRIBUTES:\n\n1. AVAILABILITY\n• Uptime (e.g., 99.9%)\n• Recovery time after failure\n\n2. PERFORMANCE\n• Response time (e.g., < 2 seconds)\n• Throughput\n• System capacity\n\n3. SECURITY\n• Authentication and authorization\n• Data encryption\n• Action auditing\n\n4. USABILITY\n• New user learning time\n• Error rate during operation\n• User satisfaction\n\n5. SCALABILITY\n\nINTERNAL ATTRIBUTES:\n• Modifiability\n• Portability\n• Testability\n• Reusability\n\nPLANGUAGE — formalized way to record quality requirements:\n'Tag: System Availability\nScale: Percentage of uptime\nMeasurement Method: 30-day monitoring\nMinimum: 99.5%\nGoal: 99.9%'",
      },
      {
        year: "II",
        image: "/images/ch15.jpg",
        sortOrder: 15,
        zhTitle: "Глава 15. Прототипы как средство снижения риска",
        zhSubtitle: "Одноразовые и эволюционные прототипы, бумажные и электронные",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Как использовать прототипирование для снижения рисков, виды прототипов, факторы успеха.",
        zhDetailContent: "ПРОТОТИП — ранняя версия продукта, созданная для проверки концепции, сбора отзывов и снижения рисков.\n\nТИПЫ ПРОТОТИПОВ:\n\n1. По долговечности:\n• Одноразовые (throwaway) — быстрые, потом выбрасываются\n• Эволюционные — постепенно превращаются в продукт\n\n2. По материалу:\n• Бумажные — скетчи, макеты на бумаге\n• Электронные — интерактивные макеты в Figma, Axure\n\nКОГДА ИСПОЛЬЗОВАТЬ:\n• Неясные или сложные требования\n• Новые пользовательские интерфейсы\n• Неизвестные технологии\n• Риски производительности\n\nПРОЦЕСС РАБОТЫ С ПРОТОТИПОМ:\n1. Определить цель прототипирования\n2. Выбрать тип прототипа\n3. Создать прототип\n4. Оценить с пользователями\n5. Документировать результаты\n\nРИСКИ:\n• Пользователи думают, что это финальный продукт\n• Команда зацикливается на деталях\n• Нереалистичные ожидания производительности\n\nФАКТОРЫ УСПЕХА:\n• Чёткая цель прототипирования\n• Привлечение правильных пользователей\n• Быстрая итерация\n• Документирование обратной связи",
        enTitle: "Chapter 15. Prototypes as a Risk Reduction Tool",
        enSubtitle: "Throwaway and evolutionary prototypes, paper and electronic",
        enCollection: "Part II — Requirements Development",
        enContent: "How to use prototyping to reduce risks, types of prototypes, success factors.",
        enDetailContent: "A PROTOTYPE is an early version of a product created to validate concepts, gather feedback, and reduce risks.\n\nTYPES OF PROTOTYPES:\n\n1. By longevity:\n• Throwaway — quick, then discarded\n• Evolutionary — gradually become the product\n\n2. By material:\n• Paper — sketches, paper mockups\n• Electronic — interactive mockups in Figma, Axure\n\nWHEN TO USE:\n• Unclear or complex requirements\n• New user interfaces\n• Unknown technologies\n• Performance risks\n\nPROTOTYPING PROCESS:\n1. Define prototyping goal\n2. Choose prototype type\n3. Create prototype\n4. Evaluate with users\n5. Document results\n\nRISKS:\n• Users think it's the final product\n• Team gets stuck on details\n• Unrealistic performance expectations\n\nSUCCESS FACTORS:\n• Clear prototyping goal\n• Involving the right users\n• Rapid iteration\n• Documenting feedback",
      },
      {
        year: "II",
        image: "/images/ch16.jpg",
        sortOrder: 16,
        zhTitle: "Глава 16. Определение приоритетов требований",
        zhSubtitle: "Зачем, как и кем расставляются приоритеты: MoSCoW, $100, попарное сравнение",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Практические методы приоритизации требований и преодоление типичных игр с приоритетами.",
        zhDetailContent: "ЗАЧЕМ ОПРЕДЕЛЯТЬ ПРИОРИТЕТЫ:\n• Ресурсы ограничены — нельзя реализовать всё\n• Помогает принимать решения при изменениях\n• Обеспечивает доставку наибольшей ценности первой\n\nПРИЁМЫ ПРИОРИТИЗАЦИИ:\n\n1. ВКЛЮЧИТЬ / НЕ ВКЛЮЧИТЬ\nПростейший метод — бинарное решение для каждого требования.\n\n2. ПОПАРНОЕ СРАВНЕНИЕ\nКаждое требование сравнивается с каждым другим. Итоговый рейтинг определяет приоритет.\n\n3. ТРЁХУРОВНЕВАЯ ШКАЛА:\n• Высокий — критично для успеха\n• Средний — важно, но можно отложить\n• Низкий — желательно, но не обязательно\n\n4. МЕТОД MoSCoW:\n• Must have — обязательно\n• Should have — желательно\n• Could have — можно, если есть время\n• Won't have — не в этой версии\n\n5. МЕТОД '100 ДОЛЛАРОВ':\nКаждый заинтересованный лицо распределяет $100 между требованиями. Требования с наибольшей суммой — высший приоритет.\n\n6. НА ОСНОВЕ ЦЕННОСТИ, СТОИМОСТИ И РИСКА:\n• Высокая ценность + Низкая стоимость = Делать первым\n• Высокая ценность + Высокая стоимость = Делать вторым\n• Низкая ценность + Низкая стоимость = Делать потом\n• Низкая ценность + Высокая стоимость = Не делать",
        enTitle: "Chapter 16. Prioritizing Requirements",
        enSubtitle: "Why, how, and by whom priorities are set: MoSCoW, $100, pairwise comparison",
        enCollection: "Part II — Requirements Development",
        enContent: "Practical methods for prioritizing requirements and overcoming typical priority games.",
        enDetailContent: "WHY PRIORITIZE:\n• Resources are limited — can't implement everything\n• Helps make decisions during changes\n• Ensures highest value is delivered first\n\nPRIORITIZATION TECHNIQUES:\n\n1. INCLUDE / EXCLUDE\nSimplest method — binary decision for each requirement.\n\n2. PAIRWISE COMPARISON\nEach requirement is compared with every other. Final ranking determines priority.\n\n3. THREE-LEVEL SCALE:\n• High — critical to success\n• Medium — important but can be delayed\n• Low — desirable but not essential\n\n4. MoSCoW METHOD:\n• Must have — mandatory\n• Should have — desirable\n• Could have — possible if time permits\n• Won't have — not in this version\n\n5. '$100' METHOD:\nEach stakeholder distributes $100 among requirements. Requirements with highest total get highest priority.\n\n6. BASED ON VALUE, COST, AND RISK:\n• High value + Low cost = Do first\n• High value + High cost = Do second\n• Low value + Low cost = Do later\n• Low value + High cost = Don't do",
      },
      {
        year: "II",
        image: "/images/ch17.jpg",
        sortOrder: 17,
        zhTitle: "Глава 17. Утверждение требований",
        zhSubtitle: "Рецензирование, верификация, критерии приёмки",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Процессы проверки и утверждения требований: экспертиза, контрольные списки, тестирование требований.",
        zhDetailContent: "УТВЕРЖДЕНИЕ ТРЕБОВАНИЙ — процесс подтверждения, что набор требований позволит создать решение, удовлетворяющее бизнес-целям.\n\nРЕЦЕНЗИРОВАНИЕ ТРЕБОВАНИЙ:\n• Неформальное — коллегиальная проверка\n• Формальное (Fagan inspection) — строгий процесс\n• Дружественное — индивидуальное чтение\n\nПРОЦЕСС ЭКСПЕРТИЗЫ (Inspection):\n1. Планирование — кто, что, когда\n2. Обзор — знакомство с материалом\n3. Подготовка — индивидуальный поиск дефектов\n4. Совещание — обсуждение найденных проблем\n5. Переработка — исправление авторами\n6. Проверка — подтверждение исправлений\n\nКОНТРОЛЬНЫЕ СПИСКИ ДЕФЕКТОВ:\n• Неоднозначность терминов\n• Неполнота требований\n• Противоречия между требованиями\n• Непроверяемость\n• Отсутствие приоритетов\n• Нет идентификаторов\n\nТЕСТИРОВАНИЕ ТРЕБОВАНИЙ:\n• Создание тестов на основе требований ДО кодирования\n• Если невозможно создать тест — требование неясное\n\nКРИТЕРИИ ПРИЁМКИ:\n• Условия, при которых заказчик примет продукт\n• Должны быть согласованы заранее\n• Связаны с бизнес-целями",
        enTitle: "Chapter 17. Requirements Validation",
        enSubtitle: "Reviews, verification, acceptance criteria",
        enCollection: "Part II — Requirements Development",
        enContent: "Processes for verifying and approving requirements: inspections, checklists, requirements testing.",
        enDetailContent: "REQUIREMENTS VALIDATION is the process of confirming that a set of requirements will enable creation of a solution that meets business goals.\n\nREQUIREMENTS REVIEWS:\n• Informal — peer review\n• Formal (Fagan inspection) — strict process\n• Friendly — individual reading\n\nINSPECTION PROCESS:\n1. Planning — who, what, when\n2. Overview — familiarization with material\n3. Preparation — individual defect finding\n4. Meeting — discussing found issues\n5. Rework — authors' corrections\n6. Follow-up — confirming corrections\n\nDEFECT CHECKLISTS:\n• Ambiguous terms\n• Incomplete requirements\n• Contradictions between requirements\n• Unverifiability\n• Missing priorities\n• No identifiers\n\nREQUIREMENTS TESTING:\n• Creating tests based on requirements BEFORE coding\n• If a test cannot be created — the requirement is unclear\n\nACCEPTANCE CRITERIA:\n• Conditions under which the customer will accept the product\n• Must be agreed upon in advance\n• Linked to business goals",
      },
      {
        year: "II",
        image: "/images/ch18.jpg",
        sortOrder: 18,
        zhTitle: "Глава 18. Повторное использование требований",
        zhSubtitle: "Зачем, как и что можно переиспользовать: семейства продуктов, схемы",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Методы повторного использования требований для ускорения разработки и повышения качества.",
        zhDetailContent: "ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ ТРЕБОВАНИЙ — применение ранее созданных требований в новых проектах. Ускоряет разработку и повышает качество.\n\nВИДЫ ПОВТОРНОГО ИСПОЛЬЗОВАНИЯ:\n\n1. ПО ОБЪЁМУ:\n• Полное — требования используются без изменений\n• Частичное — требования адаптируются\n\n2. ПО МЕХАНИЗМУ:\n• Копирование — прямое использование\n• Наследование — требования-дочки от требований-родителей\n• Параметризация — настраиваемые требования\n\nТИПЫ ИНФОРМАЦИИ ДЛЯ ПОВТОРНОГО ИСПОЛЬЗОВАНИЯ:\n• Отдельные требования\n• Характеристики (features)\n• Варианты использования\n• Правила и ограничения\n• Модели данных\n• Шаблоны документов\n\nПОПУЛЯРНЫЕ СЦЕНАРИИ:\n• Семейства продуктов (product lines)\n• Реинжиниринг и замена систем\n• Стандартные модули (аутентификация, отчётность)\n\nСХЕМЫ ТРЕБОВАНИЙ (Requirement Patterns):\n• Обобщённые шаблоны для типовых требований\n• Содержат: название, проблему, решение, примеры\n• Ускоряют создание требований\n\nФАКТОРЫ УСПЕХА:\n• Культура повторного использования в организации\n• Инструменты поиска и каталогизации\n• Документирование источников\n• Обучение команд",
        enTitle: "Chapter 18. Reusing Requirements",
        enSubtitle: "Why, how, and what to reuse: product families, patterns",
        enCollection: "Part II — Requirements Development",
        enContent: "Methods for reusing requirements to accelerate development and improve quality.",
        enDetailContent: "REQUIREMENTS REUSE — applying previously created requirements in new projects. Accelerates development and improves quality.\n\nTYPES OF REUSE:\n\n1. BY SCOPE:\n• Complete — requirements used without changes\n• Partial — requirements are adapted\n\n2. BY MECHANISM:\n• Copying — direct use\n• Inheritance — child requirements from parent requirements\n• Parameterization — configurable requirements\n\nINFORMATION TYPES FOR REUSE:\n• Individual requirements\n• Features\n• Use cases\n• Rules and constraints\n• Data models\n• Document templates\n\nPOPULAR SCENARIOS:\n• Product lines\n• Reengineering and system replacement\n• Standard modules (authentication, reporting)\n\nREQUIREMENT PATTERNS:\n• Generalized templates for typical requirements\n• Contains: name, problem, solution, examples\n• Accelerates requirement creation\n\nSUCCESS FACTORS:\n• Culture of reuse in the organization\n• Search and cataloging tools\n• Documenting sources\n• Team training",
      },
      {
        year: "II",
        image: "/images/ch19.jpg",
        sortOrder: 19,
        zhTitle: "Глава 19. От разработки требований к следующим этапам",
        zhSubtitle: "Оценка объёма, планирование, архитектура, тестирование",
        zhCollection: "Часть II — Разработка требований",
        zhContent: "Как требования влияют на последующие этапы разработки: оценку, планирование, дизайн, тестирование.",
        zhDetailContent: "ТРЕБОВАНИЯ ЯВЛЯЮТСЯ ОСНОВОЙ для всех последующих этапов разработки.\n\nОЦЕНКА ОБЪЁМА РАБОТ:\n• Требования как входные данные для оценки\n• Методы: функциональные точки, use case points, story points\n• Неопределённость уменьшается по мере уточнения требований\n\nПЛАНИРОВАНИЕ ПРОЕКТА:\n• Требования определяют объём работ\n• Приоритеты определяют порядок реализации\n• Зависимости между требованиями влияют на график\n\nАРХИТЕКТУРА И ДИЗАЙН:\n• Требования к качеству влияют на архитектурные решения\n• Функциональные требования определяют компоненты\n• Ограничения ограничивают выбор технологий\n\nТЕСТИРОВАНИЕ:\n• Требования — основа для тестовых сценариев\n• Тraceability: требование → тест → дефект\n• Приёмочное тестирование проверяет выполнение требований\n\nУПРАВЛЕНИЕ РИСКАМИ:\n• Неполные или неясные требования — главный источник рисков\n• Раннее выявление проблем снижает стоимость исправления\n• Каждое требование должно быть протестируемым\n\nУСПЕХ ПРОЕКТА:\nПроект считается успешным, когда продукт удовлетворяет требованиям в рамках бюджета и сроков.",
        enTitle: "Chapter 19. From Requirements to Next Steps",
        enSubtitle: "Estimation, planning, architecture, testing",
        enCollection: "Part II — Requirements Development",
        enContent: "How requirements influence subsequent development stages: estimation, planning, design, testing.",
        enDetailContent: "REQUIREMENTS ARE THE FOUNDATION for all subsequent development stages.\n\nEFFORT ESTIMATION:\n• Requirements as input for estimation\n• Methods: function points, use case points, story points\n• Uncertainty decreases as requirements are clarified\n\nPROJECT PLANNING:\n• Requirements define scope of work\n• Priorities determine implementation order\n• Dependencies between requirements affect schedule\n\nARCHITECTURE AND DESIGN:\n• Quality requirements influence architectural decisions\n• Functional requirements determine components\n• Constraints limit technology choices\n\nTESTING:\n• Requirements are the basis for test scenarios\n• Traceability: requirement → test → defect\n• Acceptance testing verifies requirement fulfillment\n\nRISK MANAGEMENT:\n• Incomplete or unclear requirements are the main source of risk\n• Early problem identification reduces correction cost\n• Every requirement must be testable\n\nPROJECT SUCCESS:\nA project is considered successful when the product meets requirements within budget and schedule.",
      },
      // ========== ЧАСТЬ III: Проекты определённых классов ==========
      {
        year: "III",
        image: "/images/ch20.jpg",
        sortOrder: 20,
        zhTitle: "Глава 20. Проекты гибкой разработки (Agile)",
        zhSubtitle: "Особенности работы с требованиями в Scrum, Kanban, XP",
        zhCollection: "Часть III — Проекты определённых классов",
        zhContent: "Как адаптировать приёмы работы с требованиями для проектов гибкой разработки: пользовательские истории, эпики, бэклог.",
        zhDetailContent: "ОГРАНИЧЕНИЯ ВОДОПАДНОЙ МОДЕЛИ:\n• Позднее обнаружение проблем\n• Жёсткость при изменениях\n• Недостаточная обратная связь от пользователей\n\nГИБКИЙ ПОДХОД К РАЗРАБОТКЕ:\n• Итеративная разработка\n• Постоянное взаимодействие с клиентом\n• Адаптация к изменениям\n\nОСОБЕННОСТИ ПРИМЕНЕНИЯ К ТРЕБОВАНИЯМ:\n\n1. ВОВЛЕЧЕНИЕ КЛИЕНТОВ:\n• Product Owner — представитель заказчика в команде\n• Ежедневное взаимодействие\n• Демонстрация результатов каждую итерацию\n\n2. ДОКУМЕНТАЦИЯ:\n• Минимально необходимая\n• Работающий код важнее документов\n• Лицом к лицу важнее документов\n\n3. РЕЗЕРВ ПРОЕКТА:\n• Буфер для непредвиденных требований\n• Планирование на основе скорости команды (velocity)\n\n4. ЭПИКИ, ИСТОРИИ, ФУНКЦИИ:\n• Эпик — крупная пользовательская задача\n• Пользовательская история — 'Как <роль>, я хочу <цель>, чтобы <выгода>'\n• Функция — реализуемая часть истории\n\n5. ПРИОРИТИЗАЦИЯ:\n• Product Backlog — приоритизированный список\n• Sprint Backlog — задачи на итерацию\n• Расчёт на неизбежные изменения",
        enTitle: "Chapter 20. Agile Development Projects",
        enSubtitle: "Requirements in Scrum, Kanban, XP",
        enCollection: "Part III — Specific Project Types",
        enContent: "How to adapt requirements practices for agile projects: user stories, epics, backlog.",
        enDetailContent: "WATERFALL MODEL LIMITATIONS:\n• Late problem detection\n• Rigidity with changes\n• Insufficient user feedback\n\nAGILE APPROACH:\n• Iterative development\n• Continuous client interaction\n• Adapting to changes\n\nREQUIREMENTS SPECIFICS:\n\n1. CLIENT INVOLVEMENT:\n• Product Owner — customer representative in the team\n• Daily interaction\n• Demo results every iteration\n\n2. DOCUMENTATION:\n• Minimally necessary\n• Working code over documents\n• Face-to-face over documents\n\n3. PROJECT BUFFER:\n• Buffer for unforeseen requirements\n• Planning based on team velocity\n\n4. EPICS, STORIES, FEATURES:\n• Epic — large user task\n• User story — 'As <role>, I want <goal>, so that <benefit>'\n• Feature — implementable part of a story\n\n5. PRIORITIZATION:\n• Product Backlog — prioritized list\n• Sprint Backlog — iteration tasks\n• Accounting for inevitable changes",
      },
      {
        year: "III",
        image: "/images/ch21.jpg",
        sortOrder: 21,
        zhTitle: "Глава 21. Проекты по доработке или замене систем",
        zhSubtitle: "Работа с требованиями при наличии существующей системы",
        zhCollection: "Часть III — Проекты определённых классов",
        zhContent: "Как собирать требования при модернизации или замене существующей системы: обратный инжиниринг, миграция данных.",
        zhDetailContent: "ОЖИДАЕМЫЕ ЗАТРУДНЕНИЯ:\n• Пользователи привязаны к старой системе\n• Документация устарела или отсутствует\n• Скрытая функциональность, которую 'все знают'\n• Необходимость сохранения уровня производительности\n\nРАБОТА С ТРЕБОВАНИЯМИ:\n\n1. ПРИ НАЛИЧИИ СУЩЕСТВУЮЩЕЙ СИСТЕМЫ:\n• Обратный инжиниринг — изучение кода и данных\n• Интервью с пользователями о текущих проблемах\n• Анализ отчётов и выходных данных\n\n2. РАССТАНОВКА ПРИОРИТЕТОВ:\n• На основе бизнес-целей, а не 'как было'\n• Сохранение критичной функциональности\n• Улучшение UX, а не просто копирование\n\n3. ОСТОРОЖНО С ПРОБЕЛАМИ:\n• Неявные требования, которые 'все знают'\n• Интеграции с другими системами\n• Процессы, которые не документированы\n\n4. СОХРАНЕНИЕ УРОВНЯ ПРОИЗВОДИТЕЛЬНОСТИ:\n• Бенчмаркинг текущей системы\n• Производственные требования к новой системе\n\n5. КОГДА СТАРЫХ ТРЕБОВАНИЙ НЕТ:\n• Изучение данных (схема БД, отчёты)\n• Наблюдение за пользователями\n• Анализ бизнес-процессов\n\n6. ПРОДВИЖЕНИЕ НОВОЙ СИСТЕМЫ:\n• Пилотные группы пользователей\n• Параллельная работа старой и новой систем\n• План миграции данных",
        enTitle: "Chapter 21. System Enhancement or Replacement Projects",
        enSubtitle: "Requirements work with existing systems",
        enCollection: "Part III — Specific Project Types",
        enContent: "How to gather requirements when modernizing or replacing an existing system: reverse engineering, data migration.",
        enDetailContent: "EXPECTED DIFFICULTIES:\n• Users are attached to the old system\n• Documentation is outdated or missing\n• Hidden functionality that 'everyone knows'\n• Need to maintain performance levels\n\nREQUIREMENTS WORK:\n\n1. WITH EXISTING SYSTEM:\n• Reverse engineering — studying code and data\n• User interviews about current problems\n• Analysis of reports and outputs\n\n2. PRIORITIZATION:\n• Based on business goals, not 'how it was'\n• Preserving critical functionality\n• Improving UX, not just copying\n\n3. WATCH FOR GAPS:\n• Implicit requirements that 'everyone knows'\n• Integrations with other systems\n• Undocumented processes\n\n4. MAINTAINING PERFORMANCE:\n• Benchmarking current system\n• Performance requirements for new system\n\n5. WHEN OLD REQUIREMENTS DON'T EXIST:\n• Studying data (DB schema, reports)\n• Observing users\n• Analyzing business processes\n\n6. ROLLING OUT NEW SYSTEM:\n• Pilot user groups\n• Parallel operation of old and new systems\n• Data migration plan",
      },
      {
        year: "III",
        image: "/images/ch22.jpg",
        sortOrder: 22,
        zhTitle: "Глава 22. Проекты с серийным продуктом",
        zhSubtitle: "Требования при выборе и внедрении пакетных решений",
        zhCollection: "Часть III — Проекты определённых классов",
        zhContent: "Особенности работы с требованиями при выборе и настройке готового программного обеспечения.",
        zhDetailContent: "ТРЕБОВАНИЯ К ВЫБОРУ ТИРАЖИРУЕМЫХ РЕШЕНИЙ:\n• Функциональность покрывает бизнес-потребности\n• Настраиваемость под специфику организации\n• Стоимость владения (TCO)\n• Поддержка вендора\n\nРАЗРАБОТКА ТРЕБОВАНИЙ:\n\n1. ПОЛЬЗОВАТЕЛЬСКИЕ ТРЕБОВАНИЯ:\n• Описание бизнес-процессов, которые нужно автоматизировать\n• Сравнение 'как есть' и 'как должно быть'\n\n2. БИЗНЕС-ПРАВИЛА:\n• Какие правила должна поддерживать система\n• Настройка vs доработка\n\n3. ТРЕБОВАНИЯ ПО КАЧЕСТВУ:\n• Производительность при ожидаемой нагрузке\n• Интеграция с существующими системами\n\nТРЕБОВАНИЯ К ВНЕДРЕНИЮ:\n\n• КОНФИГУРИРОВАНИЕ — настройка параметров\n• ИНТЕГРАЦИЯ — связь с другими системами\n• РАСШИРЕНИЕ — доработка под специфические нужды\n• ДАННЫЕ — миграция из старых систем\n• БИЗНЕС-ПРОЦЕССЫ — адаптация процессов под систему\n\nОБЫЧНЫЕ СЛОЖНОСТИ:\n• Пользователи хотят 'как раньше'\n• Недостаточная гибкость пакета\n• Скрытые затраты на настройку\n• Сопротивление изменению процессов",
        enTitle: "Chapter 22. Commercial Product Projects",
        enSubtitle: "Requirements for selecting and implementing packaged solutions",
        enCollection: "Part III — Specific Project Types",
        enContent: "Features of requirements work when selecting and configuring off-the-shelf software.",
        enDetailContent: "REQUIREMENTS FOR SELECTING PACKAGED SOLUTIONS:\n• Functionality covers business needs\n• Configurability for organization specifics\n• Total Cost of Ownership (TCO)\n• Vendor support\n\nREQUIREMENTS DEVELOPMENT:\n\n1. USER REQUIREMENTS:\n• Description of business processes to automate\n• Comparison of 'as is' and 'to be'\n\n2. BUSINESS RULES:\n• Which rules the system must support\n• Configuration vs customization\n\n3. QUALITY REQUIREMENTS:\n• Performance at expected load\n• Integration with existing systems\n\nIMPLEMENTATION REQUIREMENTS:\n\n• CONFIGURATION — parameter setup\n• INTEGRATION — connection with other systems\n• EXTENSION — customization for specific needs\n• DATA — migration from old systems\n• BUSINESS PROCESSES — adapting processes to the system\n\nCOMMON DIFFICULTIES:\n• Users want 'as before'\n• Insufficient package flexibility\n• Hidden customization costs\n• Resistance to process changes",
      },
      {
        year: "III",
        image: "/images/ch23.jpg",
        sortOrder: 23,
        zhTitle: "Глава 23. Проекты, выполняемые сторонними организациями",
        zhSubtitle: "Требования при аутсорсинге разработки: уровень детализации, взаимодействие",
        zhCollection: "Часть III — Проекеты определённых классов",
        zhContent: "Как формулировать требования для внешних подрядчиков, управлять изменениями и принимать результаты.",
        zhDetailContent: "НЕОБХОДИМЫЙ УРОВЕНЬ ДЕТАЛИЗАЦИИ:\n• Для фиксированной цены — максимально детальные требования\n• Для T&M (time & materials) — достаточный для понимания\n• Чем дальше подрядчик — тем детальнее требования\n\nВЗАИМОДЕЙСТВИЕ ЗАКАЗЧИКА И ПОДРЯДЧИКА:\n\n1. ДОГОВОР:\n• Объём работ (SOW) на основе требований\n• Критерии приёмки\n• Процедура изменений\n• SLAs (соглашения об уровне обслуживания)\n\n2. КОММУНИКАЦИЯ:\n• Регулярные статус-встречи\n• Демонстрации промежуточных результатов\n• Единая система отслеживания задач\n\nУПРАВЛЕНИЕ ИЗМЕНЕНИЯМИ:\n• Формализованный процесс\n• Оценка влияния на сроки и стоимость\n• Документирование всех изменений\n\nКРИТЕРИИ ПРИЁМКИ:\n• Объективные и измеримые\n• Привязаны к требованиям\n• Согласованы до начала работ\n• Включают функциональные и нефункциональные проверки",
        enTitle: "Chapter 23. Outsourced Projects",
        enSubtitle: "Requirements for external development: detail level, interaction",
        enCollection: "Part III — Specific Project Types",
        enContent: "How to formulate requirements for external contractors, manage changes, and accept results.",
        enDetailContent: "REQUIRED LEVEL OF DETAIL:\n• For fixed price — maximally detailed requirements\n• For T&M — sufficient for understanding\n• The further the contractor — the more detailed the requirements\n\nCUSTOMER-CONTRACTOR INTERACTION:\n\n1. CONTRACT:\n• Statement of Work (SOW) based on requirements\n• Acceptance criteria\n• Change procedure\n• SLAs (Service Level Agreements)\n\n2. COMMUNICATION:\n• Regular status meetings\n• Demonstrations of intermediate results\n• Unified task tracking system\n\nCHANGE MANAGEMENT:\n• Formalized process\n• Impact assessment on timeline and cost\n• Documentation of all changes\n\nACCEPTANCE CRITERIA:\n• Objective and measurable\n• Linked to requirements\n• Agreed before work begins\n• Include functional and non-functional checks",
      },
      {
        year: "III",
        image: "/images/ch24.jpg",
        sortOrder: 24,
        zhTitle: "Глава 24. Проекты автоматизации бизнес-процессов",
        zhSubtitle: "Моделирование процессов, вывод требований из текущих процессов",
        zhCollection: "Часть III — Проекты определённых классов",
        zhContent: "Как моделировать бизнес-процессы и выводить требования из текущих ('как есть') и будущих ('как должно быть') процессов.",
        zhDetailContent: "МОДЕЛИРОВАНИЕ БИЗНЕС-ПРОЦЕССОВ:\n\n1. МОДЕЛЬ 'КАК ЕСТЬ' (As-Is):\n• Документирование текущих процессов\n• Выявление узких мест и проблем\n• Понимание текущего состояния\n\n2. МОДЕЛЬ 'КАК ДОЛЖНО БЫТЬ' (To-Be):\n• Проектирование оптимизированных процессов\n• Учёт возможностей автоматизации\n• Устранение неэффективности\n\nНОТАЦИИ МОДЕЛИРОВАНИЯ:\n• BPMN (Business Process Model and Notation)\n• EPC (Event-driven Process Chain)\n• IDEF0\n\nВЫВОД ТРЕБОВАНИЙ ИЗ ПРОЦЕССОВ:\n\n1. ИЗ 'КАК ЕСТЬ':\n• Какие шаги автоматизировать\n• Какие данные нужны\n• Какие правила применяются\n\n2. ИЗ 'КАК ДОЛЖНО БЫТЬ':\n• Новые функции системы\n• Изменения в ролях пользователей\n• Интеграционные точки\n\nМЕТРИКИ БИЗНЕС-ПРОИЗВОДИТЕЛЬНОСТИ:\n• Время выполнения процесса\n• Количество ошибок\n• Стоимость процесса\n• Удовлетворённость клиентов\n\nРЕКОМЕНДУЕМЫЕ ПРИЁМЫ:\n• Вовлекать сотрудников, выполняющих процессы\n• Не просто автоматизировать — оптимизировать\n• Документировать обоснование изменений",
        enTitle: "Chapter 24. Business Process Automation Projects",
        enSubtitle: "Process modeling, deriving requirements from current processes",
        enCollection: "Part III — Specific Project Types",
        enContent: "How to model business processes and derive requirements from current ('as is') and future ('to be') processes.",
        enDetailContent: "BUSINESS PROCESS MODELING:\n\n1. AS-IS MODEL:\n• Documenting current processes\n• Identifying bottlenecks and problems\n• Understanding current state\n\n2. TO-BE MODEL:\n• Designing optimized processes\n• Accounting for automation capabilities\n• Eliminating inefficiency\n\nMODELING NOTATIONS:\n• BPMN (Business Process Model and Notation)\n• EPC (Event-driven Process Chain)\n• IDEF0\n\nDERIVING REQUIREMENTS FROM PROCESSES:\n\n1. FROM AS-IS:\n• Which steps to automate\n• What data is needed\n• What rules apply\n\n2. FROM TO-BE:\n• New system functions\n• Changes in user roles\n• Integration points\n\nBUSINESS PERFORMANCE METRICS:\n• Process execution time\n• Error count\n• Process cost\n• Customer satisfaction\n\nRECOMMENDED PRACTICES:\n• Involve employees who perform the processes\n• Don't just automate — optimize\n• Document rationale for changes",
      },
      {
        year: "III",
        image: "/images/ch25.jpg",
        sortOrder: 25,
        zhTitle: "Глава 25. Проекты бизнес-аналитики",
        zhSubtitle: "Требования к хранилищам данных, отчётности, аналитике",
        zhCollection: "Часть III — Проекты определённых классов",
        zhContent: "Разработка требований для систем бизнес-аналитики: данные, отчёты, панели мониторинга, ETL-процессы.",
        zhDetailContent: "ОБЩИЕ СВЕДЕНИЯ О ПРОЕКТАХ БИЗНЕС-АНАЛИТИКИ:\n• Хранилища данных (Data Warehouse)\n• OLAP-кубы\n• Панели мониторинга (Dashboards)\n• Самообслуживаемая аналитика\n\nРАЗРАБОТКА ТРЕБОВАНИЙ:\n\n1. ОПРЕДЕЛЕНИЕ ИСПОЛЬЗОВАНИЯ ИНФОРМАЦИИ:\n• Кто будет использовать отчёты\n• Какие решения принимаются на основе данных\n• Как часто нужны обновления\n\n2. ОПРЕДЕЛЕНИЕ ПОТРЕБНОСТЕЙ В ДАННЫХ:\n• Источники данных\n• Качество данных\n• Периодичность обновления\n• Историчность\n\n3. АНАЛИТИЧЕСКИЕ ОПЕРАЦИИ:\n• Агрегация (сумма, среднее, максимум)\n• Срезы и детализация (drill-down)\n• Сравнение периодов\n• Прогнозирование\n\nЭВОЛЮЦИОННАЯ ПРИРОДА:\n• Пользователи не всегда знают, что им нужно\n• Итеративная разработка отчётов\n• Прототипирование панелей мониторинга\n• Обратная связь drives эволюцию\n\nТРЕБОВАНИЯ К ДАННЫМ:\n• Точность и достоверность\n• Своевременность\n• Консистентность между источниками\n• Безопасность и доступность",
        enTitle: "Chapter 25. Business Intelligence Projects",
        enSubtitle: "Requirements for data warehouses, reporting, analytics",
        enCollection: "Part III — Specific Project Types",
        enContent: "Developing requirements for BI systems: data, reports, dashboards, ETL processes.",
        enDetailContent: "BUSINESS INTELLIGENCE PROJECTS OVERVIEW:\n• Data Warehouses\n• OLAP cubes\n• Dashboards\n• Self-service analytics\n\nREQUIREMENTS DEVELOPMENT:\n\n1. DEFINING INFORMATION USAGE:\n• Who will use reports\n• What decisions are made based on data\n• How often updates are needed\n\n2. DEFINING DATA NEEDS:\n• Data sources\n• Data quality\n• Update frequency\n• Historical depth\n\n3. ANALYTICAL OPERATIONS:\n• Aggregation (sum, average, maximum)\n• Slicing and drill-down\n• Period comparison\n• Forecasting\n\nEVOLUTIONARY NATURE:\n• Users don't always know what they need\n• Iterative report development\n• Dashboard prototyping\n• Feedback drives evolution\n\nDATA REQUIREMENTS:\n• Accuracy and reliability\n• Timeliness\n• Consistency across sources\n• Security and accessibility",
      },
      {
        year: "III",
        image: "/images/ch26.jpg",
        sortOrder: 26,
        zhTitle: "Глава 26. Проекты встроенных систем реального времени",
        zhSubtitle: "Требования к встроенным системам, временные характеристики, качество",
        zhCollection: "Часть III — Проекты определённых классов",
        zhContent: "Особенности разработки требований для embedded систем: временные ограничения, архитектура, надёжность.",
        zhDetailContent: "СИСТЕМНЫЕ ТРЕБОВАНИЯ ДЛЯ ВСТРОЕННЫХ СИСТЕМ:\n• Жёсткие временные ограничения (hard real-time)\n• Ограниченные ресурсы (память, процессор)\n• Высокая надёжность\n• Взаимодействие с оборудованием\n\nМОДЕЛИРОВАНИЕ:\n\n1. КОНТЕКСТНАЯ ДИАГРАММА:\n• Система и внешние устройства\n• Сенсоры, актуаторы, другие системы\n\n2. ДИАГРАММА ПЕРЕХОДОВ СОСТОЯНИЙ:\n• Реакция системы на события\n• Временные ограничения переходов\n\n3. ТАБЛИЦА СОБЫТИЙ И РЕАКЦИЙ:\n• Событие → Условие → Действие → Время отклика\n\nТРЕБОВАНИЯ К ВРЕМЕННЫМ ХАРАКТЕРИСТИКА:\n• Время отклика на событие (например, < 10 мс)\n• Периодичность опроса сенсоров\n• Задержка передачи данных\n• Джиттер (вариация задержки)\n\nАТРИБУТЫ КАЧЕСТВА:\n• Надёжность (MTBF, MTTR)\n• Безопасность (fail-safe)\n• Энергопотребление\n• Температурный диапазон\n\nПРОБЛЕМЫ:\n• Сложность тестирования на реальном оборудовании\n• Критичность ошибок\n• Интеграция аппаратного и программного обеспечения",
        enTitle: "Chapter 26. Real-Time Embedded Systems Projects",
        enSubtitle: "Requirements for embedded systems, timing, quality",
        enCollection: "Part III — Specific Project Types",
        enContent: "Features of requirements development for embedded systems: timing constraints, architecture, reliability.",
        enDetailContent: "SYSTEM REQUIREMENTS FOR EMBEDDED SYSTEMS:\n• Hard real-time constraints\n• Limited resources (memory, CPU)\n• High reliability\n• Hardware interaction\n\nMODELING:\n\n1. CONTEXT DIAGRAM:\n• System and external devices\n• Sensors, actuators, other systems\n\n2. STATE TRANSITION DIAGRAM:\n• System reaction to events\n• Timing constraints for transitions\n\n3. EVENT-RESPONSE TABLE:\n• Event → Condition → Action → Response time\n\nTIMING REQUIREMENTS:\n• Event response time (e.g., < 10 ms)\n• Sensor polling frequency\n• Data transmission delay\n• Jitter (delay variation)\n\nQUALITY ATTRIBUTES:\n• Reliability (MTBF, MTTR)\n• Safety (fail-safe)\n• Power consumption\n• Temperature range\n\nCHALLENGES:\n• Complexity of testing on real hardware\n• Criticality of errors\n• Hardware and software integration",
      },
      // ========== ЧАСТЬ IV: Управление требованиями ==========
      {
        year: "IV",
        image: "/images/ch27.jpg",
        sortOrder: 27,
        zhTitle: "Глава 27. Приёмы управления требованиями к ПО",
        zhSubtitle: "Базовая версия, отслеживание состояния, атрибуты требований",
        zhCollection: "Часть IV — Управление требованиями",
        zhContent: "Основные процессы управления требованиями: версионирование, статусы, отслеживание, разрешение проблем.",
        zhDetailContent: "ПРОЦЕСС УПРАВЛЕНИЯ ТРЕБОВАНИЯМИ:\n\n1. БАЗОВАЯ ВЕРСИЯ (Baseline):\n• Согласованный, проверенный набор требований\n• Точка отсчёта для изменений\n• Контролируется конфигурационным управлением\n\n2. УПРАВЛЕНИЕ ВЕРСИЯМИ:\n• История изменений каждого требования\n• Кто, когда, почему изменил\n• Возможность отката\n\n3. АТРИБУТЫ ТРЕБОВАНИЙ:\n• Уникальный идентификатор\n• Приоритет\n• Статус (предложено, утверждено, реализовано, проверено)\n• Автор, дата создания\n• Источник (кто запросил)\n• Стабильность (вероятность изменения)\n• Версия продукта\n\nОТСЛЕЖИВАНИЕ СОСТОЯНИЯ:\n• Матрица отслеживаемости (traceability matrix)\n• Какие требования реализованы\n• Какие протестированы\n• Какие изменены\n\nРАЗРЕШЕНИЕ ПРОБЛЕМ:\n• Регистрация проблем\n• Анализ влияния\n• Принятие решения\n• Документирование\n\nВ ПРОЕКТАХ ГИБКОЙ РАЗРАБОТКИ:\n• Меньше формальности\n• Product Backlog как средство управления\n• История изменений в системе контроля версий",
        enTitle: "Chapter 27. Software Requirements Management Practices",
        enSubtitle: "Baseline, status tracking, requirement attributes",
        enCollection: "Part IV — Requirements Management",
        enContent: "Core requirements management processes: versioning, statuses, tracking, problem resolution.",
        enDetailContent: "REQUIREMENTS MANAGEMENT PROCESS:\n\n1. BASELINE:\n• Agreed, verified set of requirements\n• Reference point for changes\n• Controlled by configuration management\n\n2. VERSION MANAGEMENT:\n• History of changes for each requirement\n• Who, when, why changed\n• Rollback capability\n\n3. REQUIREMENT ATTRIBUTES:\n• Unique identifier\n• Priority\n• Status (proposed, approved, implemented, verified)\n• Author, creation date\n• Source (who requested)\n• Stability (likelihood of change)\n• Product version\n\nSTATUS TRACKING:\n• Traceability matrix\n• Which requirements are implemented\n• Which are tested\n• Which are changed\n\nPROBLEM RESOLUTION:\n• Problem registration\n• Impact analysis\n• Decision making\n• Documentation\n\nIN AGILE PROJECTS:\n• Less formality\n• Product Backlog as management tool\n• Change history in version control system",
      },
      {
        year: "IV",
        image: "/images/ch28.jpg",
        sortOrder: 28,
        zhTitle: "Глава 28. Изменения случаются",
        zhSubtitle: "Управление изменениями: политика, процесс, совет по изменениям",
        zhCollection: "Часть IV — Управление требованиями",
        zhContent: "Как управлять изменениями требований: политика, процесс управления, совет по изменениям (CCB).",
        zhDetailContent: "ПОЧЕМУ ИЗМЕНЕНИЯ НЕИЗБЕЖНЫ:\n• Бизнес меняется\n• Пользователи лучше понимают свои потребности\n• Технологии развиваются\n• Регуляторные требования меняются\n\nПОЛИТИКА УПРАВЛЕНИЯ ИЗМЕНЕНИЯМИ:\n• Определяет, кто может запрашивать изменения\n• Как они оцениваются и утверждаются\n• Как документируются\n\nПРОЦЕСС УПРАВЛЕНИЯ ИЗМЕНЕНИЯМИ:\n\n1. НАЗНАЧЕНИЕ И ГРАНИЦЫ:\n• Что входит в процесс\n• Какие типы изменений\n\n2. РОЛИ И ОТВЕТСТВЕННОСТЬ:\n• Кто подаёт запрос\n• Кто анализирует\n• Кто принимает решение\n\n3. СОСТОЯНИЕ ЗАПРОСА:\n• Подан → В рассмотрении → Одобрен / Отклонен → Реализован\n\n4. ВХОДНЫЕ КРИТЕРИИ:\n• Форма запроса\n• Необходимая информация\n\n5. ЗАДАЧИ:\n• Анализ влияния на сроки, бюджет, качество\n• Оценка рисков\n• Определение альтернатив\n\n6. ВЫХОДНЫЕ КРИТЕРИИ:\n• Решение зафиксировано\n• Планы скорректированы\n\nСОВЕТ ПО УПРАВЛЕНИЮ ИЗМЕНЕНИЯМИ (CCB):\n• Группа принимающих решения\n• Представители заказчика, разработки, тестирования\n• Регулярные совещания\n\nАНАЛИЗ ВЛИЯНИЯ ИЗМЕНЕНИЙ:\n• Влияние на существующие требования\n• Влияние на дизайн и код\n• Влияние на тесты\n• Влияние на сроки и стоимость",
        enTitle: "Chapter 28. Changes Happen",
        enSubtitle: "Change management: policy, process, Change Control Board",
        enCollection: "Part IV — Requirements Management",
        enContent: "How to manage requirement changes: policy, management process, Change Control Board (CCB).",
        enDetailContent: "WHY CHANGES ARE INEVITABLE:\n• Business changes\n• Users better understand their needs\n• Technologies evolve\n• Regulatory requirements change\n\nCHANGE MANAGEMENT POLICY:\n• Defines who can request changes\n• How they are evaluated and approved\n• How they are documented\n\nCHANGE MANAGEMENT PROCESS:\n\n1. PURPOSE AND SCOPE:\n• What is covered by the process\n• What types of changes\n\n2. ROLES AND RESPONSIBILITIES:\n• Who submits request\n• Who analyzes\n• Who makes decision\n\n3. REQUEST STATUS:\n• Submitted → Under Review → Approved / Rejected → Implemented\n\n4. ENTRY CRITERIA:\n• Request form\n• Required information\n\n5. TASKS:\n• Impact analysis on schedule, budget, quality\n• Risk assessment\n• Alternative identification\n\n6. EXIT CRITERIA:\n• Decision is recorded\n• Plans are adjusted\n\nCHANGE CONTROL BOARD (CCB):\n• Decision-making group\n• Representatives from customer, development, testing\n• Regular meetings\n\nIMPACT ANALYSIS:\n• Impact on existing requirements\n• Impact on design and code\n• Impact on tests\n• Impact on schedule and cost",
      },
      {
        year: "IV",
        image: "/images/ch29.jpg",
        sortOrder: 29,
        zhTitle: "Глава 29. Связи в цепи требований",
        zhSubtitle: "Отслеживаемость требований: матрица, инструменты, процедура",
        zhCollection: "Часть IV — Управление требованиями",
        zhContent: "Как отслеживать связи между требованиями и другими артефактами проекта.",
        zhDetailContent: "ОТСЛЕЖИВАНИЕ СВЯЗЕЙ ТРЕБОВАНИЙ (Traceability):\n\nТИПЫ СВЯЗЕЙ:\n• Вперёд к реализации: требование → дизайн → код → тест\n• Назад к источнику: требование → бизнес-цель → заинтересованное лицо\n• Между требованиями: зависимости, конфликты\n\nМАТРИЦА ОТСЛЕЖИВАЕМОСТИ:\n• Таблица: требования × артефакты\n• Показывает, какие требования покрыты тестами\n• Выявляет 'осиротевшие' требования\n• Показывает влияние изменений\n\nСРЕДСТВА ОТСЛЕЖИВАНИЯ:\n• Специализированные инструменты (DOORS, Jama)\n• Электронные таблицы\n• Системы контроля версий\n\nПРОЦЕДУРА ОТСЛЕЖИВАНИЯ:\n1. Назначить ответственного\n2. Определить типы связей для отслеживания\n3. Создать матрицу\n4. Обновлять при изменениях\n5. Регулярно проверять\n\nПРЕИМУЩЕСТВА:\n• Уверенность в полноте реализации\n• Быстрый анализ влияния изменений\n• Упрощение регрессионного тестирования\n• Доказательство соответствия требованиям\n\nОСУЩЕСТВИМОСТЬ:\n• Требует дисциплины\n• Инструменты облегчают процесс\n• Окупается на долгосрочных проектах",
        enTitle: "Chapter 29. Links in the Requirements Chain",
        enSubtitle: "Requirements traceability: matrix, tools, procedure",
        enCollection: "Part IV — Requirements Management",
        enContent: "How to track relationships between requirements and other project artifacts.",
        enDetailContent: "REQUIREMENTS TRACEABILITY:\n\nTYPES OF LINKS:\n• Forward to implementation: requirement → design → code → test\n• Back to source: requirement → business goal → stakeholder\n• Between requirements: dependencies, conflicts\n\nTRACEABILITY MATRIX:\n• Table: requirements × artifacts\n• Shows which requirements are covered by tests\n• Reveals 'orphaned' requirements\n• Shows impact of changes\n\nTRACKING TOOLS:\n• Specialized tools (DOORS, Jama)\n• Spreadsheets\n• Version control systems\n\nTRACKING PROCEDURE:\n1. Assign responsible person\n2. Define link types to track\n3. Create matrix\n4. Update when changes occur\n5. Regular verification\n\nBENEFITS:\n• Confidence in implementation completeness\n• Quick impact analysis of changes\n• Simplified regression testing\n• Proof of requirements compliance\n\nFEASIBILITY:\n• Requires discipline\n• Tools facilitate the process\n• Pays off on long-term projects",
      },
      {
        year: "IV",
        image: "/images/ch30.jpg",
        sortOrder: 30,
        zhTitle: "Глава 30. Инструментальные средства разработки требований",
        zhSubtitle: "Средства выявления, моделирования, прототипирования и управления",
        zhCollection: "Часть IV — Управление требованиями",
        zhContent: "Обзор инструментов для работы с требованиями: от простых до корпоративных систем управления.",
        zhDetailContent: "КАТЕГОРИИ ИНСТРУМЕНТОВ:\n\n1. СРЕДСТВА ВЫЯВЛЕНИЯ:\n• Инструменты для интервью и семинаров\n• Опросники и анкеты\n• Системы видеоконференций\n\n2. СРЕДСТВА СОЗДАНИЯ ПРОТОТИПОВ:\n• Figma, Sketch, Adobe XD — UI/UX\n• Axure RP — интерактивные прототипы\n• Balsamiq — wireframes\n\n3. СРЕДСТВА МОДЕЛИРОВАНИЯ:\n• Visio, draw.io — диаграммы\n• Enterprise Architect — UML, BPMN\n• Lucidchart — совместное моделирование\n\n4. СРЕДСТВА УПРАВЛЕНИЯ ТРЕБОВАНИЯМИ:\n• IBM DOORS — enterprise-уровень\n• Jama Connect — для сложных продуктов\n• Jira + плагины — для гибкой разработки\n• Azure DevOps — от Microsoft\n\nПРЕИМУЩЕСТВА ИСПОЛЬЗОВАНИЯ СРЕДСТВ:\n• Централизованное хранение\n• Контроль версий\n• Отслеживание связей\n• Совместная работа\n• Отчётность\n\nВЫБОР ИНСТРУМЕНТА:\n• Размер и сложность проекта\n• Количество заинтересованных лиц\n• Бюджет\n• Интеграция с существующими инструментами\n\nОСВОЕНИЕ:\n• Обучение пользователей\n• Настройка под процессы\n• Постепенное внедрение",
        enTitle: "Chapter 30. Requirements Development Tools",
        enSubtitle: "Elicitation, modeling, prototyping, and management tools",
        enCollection: "Part IV — Requirements Management",
        enContent: "Overview of tools for working with requirements: from simple to enterprise management systems.",
        enDetailContent: "TOOL CATEGORIES:\n\n1. ELICITATION TOOLS:\n• Interview and workshop tools\n• Surveys and questionnaires\n• Video conferencing systems\n\n2. PROTOTYPING TOOLS:\n• Figma, Sketch, Adobe XD — UI/UX\n• Axure RP — interactive prototypes\n• Balsamiq — wireframes\n\n3. MODELING TOOLS:\n• Visio, draw.io — diagrams\n• Enterprise Architect — UML, BPMN\n• Lucidchart — collaborative modeling\n\n4. REQUIREMENTS MANAGEMENT TOOLS:\n• IBM DOORS — enterprise level\n• Jama Connect — for complex products\n• Jira + plugins — for agile development\n• Azure DevOps — from Microsoft\n\nBENEFITS OF USING TOOLS:\n• Centralized storage\n• Version control\n• Link tracking\n• Collaboration\n• Reporting\n\nTOOL SELECTION:\n• Project size and complexity\n• Number of stakeholders\n• Budget\n• Integration with existing tools\n\nADOPTION:\n• User training\n• Process customization\n• Gradual implementation",
      },
      // ========== ЧАСТЬ V: Реализация процесса ==========
      {
        year: "V",
        image: "/images/ch31.jpg",
        sortOrder: 31,
        zhTitle: "Глава 31. Совершенствование процессов работы с требованиями",
        zhSubtitle: "Анализ первопричин, цикл совершенствования, дорожная карта",
        zhCollection: "Часть V — Реализация процесса",
        zhContent: "Как внедрить и совершенствовать процессы работы с требованиями в организации.",
        zhDetailContent: "КАК ТРЕБОВАНИЯ СВЯЗАНЫ С ДРУГИМИ СОСТАВЛЯЮЩИМИ ПРОЕКТА:\n• Планирование — требования определяют объём\n• Дизайн — требования как входные данные\n• Разработка — реализация требований\n• Тестирование — проверка требований\n• Поддержка — требования как документация\n\nОСНОВЫ СОВЕРШЕНСТВОВАНИЯ ПРОЦЕССОВ:\n\n1. АНАЛИЗ ПЕРВОПРИЧИН:\n• Почему возникают проблемы с требованиями\n• 5 Whys — метод пяти 'почему'\n• Ищем корень, а не симптом\n\n2. ЦИКЛ СОВЕРШЕНСТВОВАНИЯ:\n• Оценка текущих приёмов\n• Планирование действий\n• Создание и проба новых процессов\n• Оценка результатов\n\n3. ДОРОЖНАЯ КАРТА:\n• Что улучшать первым\n• Краткосрочные и долгосрочные цели\n• Метрики успеха\n\nДОКУМЕНТЫ ПРОЦЕССА:\n\nПроцесс разработки требований:\n• Как выявлять требования\n• Как документировать\n• Кто проверяет\n• Критерии качества\n\nПроцесс управления требованиями:\n• Как управлять изменениями\n• Как отслеживать состояние\n• Кто принимает решения\n\nДОСТИГНУТА ЛИ ЦЕЛЬ:\n• Меньше дефектов в требованиях\n• Меньше переделок\n• Удовлетворённость клиентов\n• Соблюдение сроков и бюджета",
        enTitle: "Chapter 31. Improving Requirements Processes",
        enSubtitle: "Root cause analysis, improvement cycle, roadmap",
        enCollection: "Part V — Process Implementation",
        enContent: "How to implement and improve requirements processes in an organization.",
        enDetailContent: "HOW REQUIREMENTS RELATE TO OTHER PROJECT COMPONENTS:\n• Planning — requirements define scope\n• Design — requirements as input\n• Development — implementing requirements\n• Testing — verifying requirements\n• Support — requirements as documentation\n\nPROCESS IMPROVEMENT BASICS:\n\n1. ROOT CAUSE ANALYSIS:\n• Why do requirements problems occur\n• 5 Whys method\n• Find the root, not the symptom\n\n2. IMPROVEMENT CYCLE:\n• Assess current practices\n• Plan actions\n• Create and test new processes\n• Evaluate results\n\n3. ROADMAP:\n• What to improve first\n• Short-term and long-term goals\n• Success metrics\n\nPROCESS DOCUMENTS:\n\nRequirements development process:\n• How to elicit requirements\n• How to document\n• Who reviews\n• Quality criteria\n\nRequirements management process:\n• How to manage changes\n• How to track status\n• Who makes decisions\n\nGOAL ACHIEVED:\n• Fewer requirement defects\n• Less rework\n• Customer satisfaction\n• Meeting schedule and budget",
      },
      {
        year: "V",
        image: "/images/ch32.jpg",
        sortOrder: 32,
        zhTitle: "Глава 32. Требования к ПО и управление рисками",
        zhSubtitle: "Риски, связанные с требованиями, и методы их управления",
        zhCollection: "Часть V — Реализация процесса",
        zhContent: "Заключительная глава о связи между требованиями и управлением рисками в проектах разработки ПО.",
        zhDetailContent: "ОСНОВЫ УПРАВЛЕНИЯ РИСКАМИ:\n• Риск — потенциальная проблема, которая может возникнуть\n• Управление рисками — проактивная деятельность\n• Цель — минимизировать негативное влияние\n\nСОСТАВЛЯЮЩИЕ УПРАВЛЕНИЯ РИСКАМИ:\n1. Идентификация — что может пойти не так\n2. Анализ — вероятность и влияние\n3. Планирование — что делать\n4. Мониторинг — отслеживание\n\nРИСКИ, СВЯЗАННЫЕ С ТРЕБОВАНИЯМИ:\n\n1. ВЫЯВЛЕНИЕ ТРЕБОВАНИЙ:\n• Недостаточное вовлечение пользователей\n• Неправильное понимание бизнес-целей\n• Пропущенные заинтересованные лица\n\n2. АНАЛИЗ ТРЕБОВАНИЙ:\n• Неполнота анализа\n• Неверные приоритеты\n• Неучтённые зависимости\n\n3. СПЕЦИФИКАЦИЯ:\n• Неоднозначность\n• Неполнота\n• Противоречивость\n\n4. УТВЕРЖДЕНИЕ:\n• Недостаточное рецензирование\n• Отсутствие приёмочных критериев\n\n5. УПРАВЛЕНИЕ ТРЕБОВАНИЯМИ:\n• Неконтролируемые изменения\n• Потеря отслеживаемости\n• Недостаточная коммуникация\n\nУПРАВЛЕНИЕ РИСКАМИ — ВАШ ДРУГ:\n• Раннее выявление проблем\n• Проактивные действия\n• Уверенность в проекте\n• Успешная доставка продукта",
        enTitle: "Chapter 32. Software Requirements and Risk Management",
        enSubtitle: "Requirements-related risks and their management methods",
        enCollection: "Part V — Process Implementation",
        enContent: "Final chapter on the relationship between requirements and risk management in software development projects.",
        enDetailContent: "RISK MANAGEMENT BASICS:\n• Risk — a potential problem that may occur\n• Risk management — proactive activity\n• Goal — minimize negative impact\n\nRISK MANAGEMENT COMPONENTS:\n1. Identification — what could go wrong\n2. Analysis — probability and impact\n3. Planning — what to do\n4. Monitoring — tracking\n\nREQUIREMENTS-RELATED RISKS:\n\n1. ELICITATION:\n• Insufficient user involvement\n• Incorrect understanding of business goals\n• Missed stakeholders\n\n2. ANALYSIS:\n• Incomplete analysis\n• Wrong priorities\n• Unaccounted dependencies\n\n3. SPECIFICATION:\n• Ambiguity\n• Incompleteness\n• Contradictions\n\n4. VALIDATION:\n• Insufficient review\n• Missing acceptance criteria\n\n5. REQUIREMENTS MANAGEMENT:\n• Uncontrolled changes\n• Lost traceability\n• Insufficient communication\n\nRISK MANAGEMENT IS YOUR FRIEND:\n• Early problem detection\n• Proactive actions\n• Confidence in the project\n• Successful product delivery",
      },
    ];

    for (const post of seedPosts) {
      await getDb().insert(posts).values(post);
    }
    console.log(`  Seeded ${seedPosts.length} chapters`);
  } else {
    console.log("  Posts already seeded");
  }

  // 3. Seed profile bio
  const existingBio = await getDb().select().from(profileBio);
  if (existingBio.length === 0) {
    await getDb().insert(profileBio).values({
      id: 1,
      zhText: "Карл Вигерс — признанный эксперт в области разработки требований к программному обеспечению. Книга 'Разработка требований к программному обеспечению' (Software Requirements) является одним из ключевых руководств в области бизнес-анализа и управления требованиями. Третье издание, дополненное Джой Битти, включает приёмы работы с требованиями в проектах гибкой разработки (Agile). Книга состоит из 32 глав, охватывающих все аспекты работы с требованиями — от основ и определений до управления рисками и совершенствования процессов.",
      enText: "Karl Wiegers is a recognized expert in software requirements development. His book 'Software Requirements' is one of the key guides in business analysis and requirements management. The third edition, updated by Joy Beatty, includes practices for agile development projects. The book consists of 32 chapters covering all aspects of requirements work — from fundamentals and definitions to risk management and process improvement.",
      email: "info@processimpact.com",
      instagram: "https://processimpact.com",
    });
    console.log("  Seeded profile bio");
  } else {
    console.log("  Profile bio already exists");
  }

  // 4. Seed CV entries (book parts structure)
  const existingCv = await getDb().select().from(cvEntries);
  if (existingCv.length === 0) {
    const seedCv = [
      { category: "Structure", zhTitle: "Часть I: Требования к ПО — что, почему и кто", zhSubtitle: "Главы 1–4: Основы, клиентская перспектива, приёмы, роль аналитика", enTitle: "Part I: Software Requirements — What, Why and Who", enSubtitle: "Chapters 1–4: Fundamentals, customer perspective, practices, analyst role", year: "2024", sortOrder: 1 },
      { category: "Structure", zhTitle: "Часть II: Разработка требований", zhSubtitle: "Главы 5–19: Бизнес-требования, пользователи, выявление, документирование, качество, прототипы, приоритеты, утверждение, повторное использование", enTitle: "Part II: Requirements Development", enSubtitle: "Chapters 5–19: Business requirements, users, elicitation, documentation, quality, prototypes, priorities, validation, reuse", year: "2024", sortOrder: 2 },
      { category: "Structure", zhTitle: "Часть III: Требования в проектах определённых классов", zhSubtitle: "Главы 20–26: Agile, замена систем, пакетные решения, аутсорсинг, автоматизация процессов, BI, встроенные системы", enTitle: "Part III: Specific Project Types", enSubtitle: "Chapters 20–26: Agile, system replacement, COTS, outsourcing, process automation, BI, embedded systems", year: "2024", sortOrder: 3 },
      { category: "Structure", zhTitle: "Часть IV: Управление требованиями", zhSubtitle: "Главы 27–30: Приёмы управления, изменения, отслеживаемость, инструменты", enTitle: "Part IV: Requirements Management", enSubtitle: "Chapters 27–30: Management practices, changes, traceability, tools", year: "2024", sortOrder: 4 },
      { category: "Structure", zhTitle: "Часть V: Реализация процесса построения требований", zhSubtitle: "Главы 31–32: Совершенствование процессов, управление рисками", enTitle: "Part V: Process Implementation", enSubtitle: "Chapters 31–32: Process improvement, risk management", year: "2024", sortOrder: 5 },
      { category: "Details", zhTitle: "Издание", zhSubtitle: "3-е издание, дополненное", enTitle: "Edition", enSubtitle: "3rd Edition, Updated", year: "2014", sortOrder: 6 },
      { category: "Details", zhTitle: "Авторы", zhSubtitle: "Карл Вигерс и Джой Битти", enTitle: "Authors", enSubtitle: "Karl Wiegers and Joy Beatty", year: "2014", sortOrder: 7 },
      { category: "Details", zhTitle: "Объём", zhSubtitle: "736 страниц, 32 главы, 3 приложения, словарь терминов", enTitle: "Volume", enSubtitle: "736 pages, 32 chapters, 3 appendices, glossary", year: "2014", sortOrder: 8 },
      { category: "Details", zhTitle: "ISBN", zhSubtitle: "978-5-7502-0433-5 (Русская редакция)", enTitle: "ISBN", enSubtitle: "978-0-7356-7966-5 (Original)", year: "2014", sortOrder: 9 },
    ];
    for (const cv of seedCv) {
      await getDb().insert(cvEntries).values(cv);
    }
    console.log(`  Seeded ${seedCv.length} CV entries`);
  } else {
    console.log("  CV entries already exist");
  }

  // 5. Seed site settings
  const existingSettings = await getDb().select().from(siteSettings);
  if (existingSettings.length === 0) {
    await getDb().insert(siteSettings).values({
      id: 1,
      avatarImage: "/images/portrait.jpg",
    });
    console.log("  Seeded site settings");
  } else {
    console.log("  Site settings already exist");
  }

  console.log("Seed complete!");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
